import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export default function Home() {
  return (

    <div className={styles.container}>
      
      <Navbar/>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <h1 className={styles.title}>
          WELCOME A <a href="https://nextjs.org">SUPREME!</a>
        </h1>

        <p className={styles.description}>
        A Supreme é uma loja virtual pensada para atender você da melhor forma possível.

        Os produtos são enviados da nossa sede em São Paulo para seu endereço cadastrado.

        Simples, barato e seguro! Os produtos selecionados pelos nossos consultores seguem um alto padrão de qualidade.

        Buscamos estar atualizados sempre com as novas tendências da moda e os mais variados produtos. Fique por dentro da moda e economize tempo e dinheiro.

        A Supreme está aqui para te oferecer o melhor que o mundo tem a oferecer!
        </p>

        <div className={styles.grid}>
          <a href="/produtos" className={styles.card}>
            <h2>Produtos &rarr;</h2>
            <p>Conheça os produtos da nossa loja.</p>
          </a>

          <Footer/>

        </div>
      </main>
    </div>
  )
}
