import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { AiFillCaretDown } from "react-icons/ai";
import { BiStoreAlt } from "react-icons/bi";
import { AiOutlineSafety } from "react-icons/ai";
import { MdOutlineTipsAndUpdates } from "react-icons/md";

export default function Home() {
  return (

    <div className={styles.container}>
      

      <Head>
        <title>Loja Supreme - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.gradient}>
          <Navbar/>
          <div className={styles.ctaSection}>
            <h1 className={styles.title}>
              BOAS-VINDAS A <a href="https://nextjs.org">SUPREME!</a>
            </h1>

            <a href="/produtos" className={styles.ctaBtn}>
              EXPLORE A LOJA
            </a>
          </div>

          <div className={styles.ctdSection}>
            <a href="#about">
              <p>SAIBA MAIS</p>
              <AiFillCaretDown />
            </a>
          </div>
        </div>
      </main>

      <section id="about" className={styles.description}>
        
        <p className={styles.topDesc}>A Supreme está aqui para te oferecer o melhor que o mundo tem a oferecer!</p>
        
        <div className={styles.boxes}>
          <div className={styles.descBox}>
            <BiStoreAlt />
            <p>A Supreme é uma loja virtual pensada para atender você da melhor forma possível.</p>
          </div>

          <div className={styles.descBox}>
            <AiOutlineSafety />
            <p>
              Os produtos são enviados da nossa sede em São Paulo para seu endereço cadastrado.
              Simples, barato e seguro! Os produtos selecionados pelos nossos consultores seguem um alto padrão de qualidade.
            </p>
          </div>

          <div className={styles.descBox}>
            <MdOutlineTipsAndUpdates />
            <p>
              Buscamos estar atualizados sempre com as novas tendências da moda e os mais variados produtos.
              Fique por dentro da moda e economize tempo e dinheiro.
            </p>
          </div>
        </div>

      </section>

        <div className={styles.grid}>

          <Footer/>

        </div>
    </div>
  )
}
